title: Wenzhe Cao's Homepage
page-top-title: User Name
top-section-bg-text: Mathematics
backgrounds:
  - static/assets/background/background_0.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Wenzhe Cao 2023-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/wenzhecao205
license-link:
  text: License
  href: https://github.com/wenzhecao205/wenzhecao205.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: UWenzhe Cao;|&ensp;曹文哲
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
